# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lien's Blog
tagline:             'ReactJS, ReactNative, .NET, SQL, GraphQL, Python'
description:         'Have a nice day, guys!'
url:                 http://lanyon.getpoole.com
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Đinh Trọng Liên
  url:               https://www.facebook.com/dinhtronglien
  email:             dinhtronglien710@gmail.com

# Custom vars
version:             1.0.0
